Key numbers
CartONG/SOSMedDashboard pull request #24
Opened 2022-02-13 19:18 UTC by WesleyTheGeolien

2022-02-13 19:18 UTC, WesleyTheGeolien commented
Image attached to message
J'ai fait un premier jet de Key stats, SI jai bien compris les valeurs sont fixes (ne depend pas de Histogram)?

Le 2016 est hard coded (je ne sais pas si ca devrait etre dynamique.

Par contre jai un peu de mal pour la mise en page jai limpression quon fait des choses en absolue or, ca aurait ete bien en relatif vis a vis du header je trouve, je ne sais pas ce que les autre en pensent?

2022-02-16 16:34 UTC, NicolasGrosjean commented
> Par contre jai un peu de mal pour la mise en page j'ai limpression qu'on fait des choses en absolue or, ca aurait été bien en relatif vis a vis du header je trouve, je ne sais pas ce que les autre en pensent ?

Je pense que ça serait bien ou alors en relatif vis-à-vis de la BaseMap si c'est plus simple à implémenter.

2022-02-16 16:38 UTC, NicolasGrosjean requested changes
Les outils de navigation devraient en dessous de l'encart des chiffres clés

Maquette : 
![image](https://user-images.githubusercontent.com/13560473/154312646-6e86462d-eb91-4117-9ca6-355200641333.png)

Actuel :
![image](https://user-images.githubusercontent.com/13560473/154312839-7f76b304-e84b-49c9-b4d4-aba61912b41e.png)

2022-04-10 12:16 UTC, NicolasGrosjean commented
Dans 43d842b, j'arrive à avoir un rendu proche de la maquette :

![image](https://user-images.githubusercontent.com/13560473/162617515-2a9a5699-525d-49a9-8bc8-c11785c7ea05.png)

Par contre, je trouve le code pour y arriver super crade. @regazzoj tu as des idées pour faire plus propre ?

2022-04-11 09:44 UTC, regazzoj commented
> Dans [43d842b](https://github.com/CartONG/SOSMedDashboard/commit/43d842b9e5b6845a2054d0b6625381a4497ac3b6), j'arrive à avoir un rendu proche de la maquette :
> 
> ![image](https://user-images.githubusercontent.com/13560473/162617515-2a9a5699-525d-49a9-8bc8-c11785c7ea05.png)
> 
> Par contre, je trouve le code pour y arriver super crade. @regazzoj tu as des idées pour faire plus propre ?

Je ne suis pas sûr de voir ce qui te dérange. Peux-tu me dire ce que tu trouves crade s'il te plaît ?

2022-04-11 09:44 UTC, regazzoj commented on src/components/KeyNumbers.vue
> +  data () {
À supprimer car inutilisé par le composant

2022-04-11 20:48 UTC, NicolasGrosjean commented
> > Dans [43d842b](https://github.com/CartONG/SOSMedDashboard/commit/43d842b9e5b6845a2054d0b6625381a4497ac3b6), j'arrive à avoir un rendu proche de la maquette :
> > ![image](https://user-images.githubusercontent.com/13560473/162617515-2a9a5699-525d-49a9-8bc8-c11785c7ea05.png)
> > Par contre, je trouve le code pour y arriver super crade. @regazzoj tu as des idées pour faire plus propre ?
> 
> Je ne suis pas sûr de voir ce qui te dérange. Peux-tu me dire ce que tu trouves crade s'il te plaît ?

Je surcharge une classe masquée par l'API mapbox (mapboxgl-ctrl-top-right) avec le code source de md: de tailwind (@media (min-width: 768px), donc 2 éléments sur lesquels on n'a pas du tout la main et qui peuvent changer sans crier gare.

2022-04-12 19:42 UTC, regazzoj commented
> > > Dans [43d842b](https://github.com/CartONG/SOSMedDashboard/commit/43d842b9e5b6845a2054d0b6625381a4497ac3b6), j'arrive à avoir un rendu proche de la maquette :
> > > ![image](https://user-images.githubusercontent.com/13560473/162617515-2a9a5699-525d-49a9-8bc8-c11785c7ea05.png)
> > > Par contre, je trouve le code pour y arriver super crade. @regazzoj tu as des idées pour faire plus propre ?
> > 
> > 
> > Je ne suis pas sûr de voir ce qui te dérange. Peux-tu me dire ce que tu trouves crade s'il te plaît ?
> 
> Je surcharge une classe masquée par l'API mapbox (mapboxgl-ctrl-top-right) avec le code source de md: de tailwind (@media (min-width: 768px), donc 2 éléments sur lesquels on n'a pas du tout la main et qui peuvent changer sans crier gare.

Okay, je vois,
Tu peux faire comme à la place `@screen md {
  .mapboxgl-ctrl-top-right  {
    top: 22%;
    right: 1em;
  }
}
`
Cela permet d'utilier les media de TailWind.
Après, je trouve ça aussi dommage de devoir surcharger cette classe mais je n'ai pas de meilleure solution.

2022-04-13 08:06 UTC, NicolasGrosjean commented on src/components/KeyNumbers.vue
> +  data () {
Corrigé par 0bbbc62

2022-04-13 08:09 UTC, NicolasGrosjean approved these changes
Cela me paraît tout bon.

On a juste des problèmes quand l'écran est bien plus large que haut, mais on a des problèmes bien plus grave à gérer avec l'histogramme dans ce cas en priorité, et puis on pourra gérer ça plus tard avec la prochaine version du header.

![image](https://user-images.githubusercontent.com/13560473/163130424-c7557b4d-e111-4530-8444-5db3c89f2754.png)

2022-05-06 11:00 UTC, NicolasGrosjean commented
On a décidé avec @regazzoj et @etienne-cartong que @regazzoj fasse la version mobile dans cette branche donc on ne la squash pas pour le moment.

On la squashera avant le 18 juin s'il faut.

2022-12-05 18:25 UTC, regazzoj approved these changes

2022-12-05 19:41 UTC, merged