Feature/add i18n
CartONG/SOSMedDashboard pull request #28
Opened 2022-05-06 15:55 UTC by etienne-cartong

i18n ajouté. Ave le fichier de traduction fr.json

Une revue des traduction reste à faire par SosMed ou CartONG. Dans une autre tâche. 
C'était du vrai franglish. 

Concernant les dates, les nombres, etc -> faisable. Mais: pourquoi ce ne sont pas des variables du store, mais l'utilisation de setInnerText? C'est un frein à l'application de méthode de rendu type: {{ $n(NOMBRE) }}

A voir.. Satisfaisant en attendant.

2022-05-07 06:49 UTC, NicolasGrosjean commented
Quelle efficacité !

Pour les dates, j'ai besoin que ça soit un State vu que ça change toutes les données et qu'elles sont modifiées dans un autre composant : l'histogramme.

Pour les nombres, j'ai créé la fonction `numberToString `pour gérer les données manquantes et j'ai utilisé `setInnerText` pour appliquer le résultat dans le HTML.
Ce projet est mon 1er projet en Vue, il y a donc une meilleure manière de faire ça que j'ignore.
N'hésite pas à tout casser si tu as une manière de faire compatible avec i18n qui permettra de mettre un séparateur des milliers (espace en français et virgule en anglais).

2022-05-07 06:54 UTC, NicolasGrosjean requested changes

2022-05-07 06:54 UTC, NicolasGrosjean commented on src/locales/fr.json
> +    },
Il y a encore de l'anglais ici

2022-05-07 06:54 UTC, NicolasGrosjean commented on src/locales/fr.json
> +        "unaccompagned": "Isolé",
`pregnant `et `unaccompagned `sont traduits par un mot au singulier alors que tous les autres sont au pluriel.

2022-05-07 06:55 UTC, NicolasGrosjean commented
PopUp.vue a encore ses textes écrits en dur

2022-05-23 13:33 UTC, etienne-cartong commented
J'ai commencé très efficace, puis je suis parti en congés.
J'ai appliqué les deux trois correctifs (popup, et franglish).
J'essaye de proposer un truc pour la traduction date + nombre dans la semaine.

2022-06-07 20:00 UTC, NicolasGrosjean requested changes
J'ai mis à jour master pour traduire les nouveaux textes (n'hésite pas à les améliorer) et j'ai corrigé le bug du bouton donation.

En plus des dates et nombres dont tu parlais, j'ai noté que les textes des boutons de la carte sont en anglais.
Cela vaut le coup de les traduire avec i18n ou si on y arrive pas en français en dur mais ça serait triste.

2022-06-08 09:17 UTC, etienne-cartong commented
> J'ai mis à jour master pour traduire les nouveaux textes (n'hésite pas à les améliorer) et j'ai corrigé le bug du bouton donation.
> 
> En plus des dates et nombres dont tu parlais, j'ai noté que les textes des boutons de la carte sont en anglais. Cela vaut le coup de les traduire avec i18n ou si on y arrive pas en français en dur mais ça serait triste.

Les traductions doivent être faites avec l'api mapbox. il me semble qu'il faut que le style soit éditable, je vais me renseigner un peu. 
Je propose qu'on merge cette partie en attendant, Ça servira de support pour faire valider les traductions courantes (par les non devs et sosmed), et d'intégrer aussi la traduction aux choses développées depuis, comme les contributors. 
Ça te parait cohérent ?

2022-06-08 18:34 UTC, NicolasGrosjean commented
> > J'ai mis à jour master pour traduire les nouveaux textes (n'hésite pas à les améliorer) et j'ai corrigé le bug du bouton donation.
> > En plus des dates et nombres dont tu parlais, j'ai noté que les textes des boutons de la carte sont en anglais. Cela vaut le coup de les traduire avec i18n ou si on y arrive pas en français en dur mais ça serait triste.
> 
> Les traductions doivent être faites avec l'api mapbox. il me semble qu'il faut que le style soit éditable, je vais me renseigner un peu. Je propose qu'on merge cette partie en attendant, Ça servira de support pour faire valider les traductions courantes (par les non devs et sosmed), et d'intégrer aussi la traduction aux choses développées depuis, comme les contributors. Ça te parait cohérent ?

Je plussoie !

Je te laisse faire un merge ou un squash.

Encore une fois n'hésite pas

2022-06-08 18:35 UTC, NicolasGrosjean approved these changes

2022-06-08 22:35 UTC, merged